[23/May/2014 12:09:35] DEBUG [monitoring.views:170] Sensores para módulo 2.2: {'temperatura': {'valor': '20', 'interesse': 'temperatura'}}
[23/May/2014 12:09:35] DEBUG [monitoring.views:89] Definindo estado para o módulo 2.2
[23/May/2014 12:09:35] DEBUG [monitoring.views:194] Estado para o sensor temperatura: Ativo
[23/May/2014 12:09:35] DEBUG [monitoring.views:157] Pesos dos sensores do módulo 2.2: [2]
[23/May/2014 12:09:35] DEBUG [monitoring.views:106] Estado do módulo atualizado para: Ativo
[23/May/2014 12:09:35] DEBUG [monitoring.views:222] ERROR: interesse umidade-interesse não é o mesmo da API umidade
[23/May/2014 12:09:35] DEBUG [monitoring.views:194] Estado para o sensor umidade: Falha de Operação
[23/May/2014 12:09:35] DEBUG [monitoring.views:222] ERROR: interesse umidade-interesse não é o mesmo da API umidade
[23/May/2014 12:09:35] DEBUG [monitoring.views:219] ERROR: a leitura retornada não pôde ser traduzida.                     
 Leitura: set(['random']) 
 Erro: Traceback (most recent call last):
  File "/Users/lfrias/Dropbox/Faculdade/ESOO/Painel de Controle/painel/monitoring/views.py", line 215, in parse
    self._parse()
  File "/Users/lfrias/Dropbox/Faculdade/ESOO/Painel de Controle/painel/monitoring/views.py", line 206, in _parse
    self.name = self.leitura['interesse']
TypeError: 'set' object has no attribute '__getitem__'

[23/May/2014 12:09:35] DEBUG [monitoring.views:194] Estado para o sensor fumaca: Falha de Operação
[23/May/2014 12:09:35] DEBUG [monitoring.views:219] ERROR: a leitura retornada não pôde ser traduzida.                     
 Leitura: set(['random']) 
 Erro: Traceback (most recent call last):
  File "/Users/lfrias/Dropbox/Faculdade/ESOO/Painel de Controle/painel/monitoring/views.py", line 215, in parse
    self._parse()
  File "/Users/lfrias/Dropbox/Faculdade/ESOO/Painel de Controle/painel/monitoring/views.py", line 206, in _parse
    self.name = self.leitura['interesse']
TypeError: 'set' object has no attribute '__getitem__'

